version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cyber_intelligence
      POSTGRES_USER: cyber_user
      POSTGRES_PASSWORD: cyber_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cyber_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - cyber_network

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://cyber_user:cyber_pass@db:5432/cyber_intelligence
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - ./config:/app/config
    networks:
      - cyber_network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - cyber_network

volumes:
  postgres_data:

networks:
  cyber_network:
    driver: bridge